name: haskell-dsa
version: 0.1.0.0
dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  haskell-dsa-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - haskell-dsa
      - hspec
